#!/home/kill/aipyapp/venv/bin/python3
import sys
from midi2audio import main_play
if __name__ == '__main__':
    if sys.argv[0].endswith('.exe'):
        sys.argv[0] = sys.argv[0][:-4]
    sys.exit(main_play())
