"""
Nihiline Recursion — Full Analysis
==================================
Four moves:

  1. Replace pseudo-random phase scrambling with deterministic chaos
     generated by the system's own state — honest within the numerical
     ontology. The "scrambling" is feedback through a nonlinear map,
     not injected randomness.

  2. Compute S_n as information gain per cycle (Shannon entropy of the
     cycle-trajectory distribution), not as a binary success ratio.

  3. Joint sweep C × nihil fraction: does high-control require less
     nothing than low-control?

  4. Sweep ω_r / ω_d ratio at optimum nihil: find ratios where
     cross-sweeping produces standing/pattern structures vs recursive
     ergodic trajectories. Pattern = closed orbit in phase space.
     Recursion = ergodic filling.
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.fft import fft

# ============================================================
# Core simulator with deterministic chaotic phase generation
# ============================================================
def simulate(C, omega_d=2.0, omega_r=3.2, f_nihil=0.10,
             M_strength=0.95, T=30.0, dt=0.001,
             psi0=1.0 + 0j, phase_seed=0.4123):
    """
    Phase of each rebirth kick is generated by a logistic map
    iterated on the prior cycle's pre-nihil state — deterministic,
    bounded, chaotic for r in the chaotic regime. No PRNG.

    The "randomness" of decoherence is the system's own nonlinearity
    feeding back through the substrate.
    """
    period_r = 2*np.pi / omega_r
    nihil_dur = f_nihil * period_r
    nihil_steps = int(nihil_dur / dt)

    t = np.arange(0, T, dt)
    gamma = (1.0 - C) * 4.0

    rebirth_times = np.arange(period_r/2, T, period_r)
    rebirth_idx = (rebirth_times / dt).astype(int)
    rebirth_idx = rebirth_idx[rebirth_idx < len(t)]

    # Logistic-map chaotic regime r in [3.7, 4.0] — fully deterministic
    # Modulated by (1-C): high control = phases stay near attractor;
    # low control = phases scatter chaotically across [0, 2π]
    logistic_r = 3.7 + 0.29 * (1.0 - C)   # higher chaos for low C
    chaos_state = phase_seed

    nihil_mask = np.zeros(len(t), dtype=bool)
    for ri in rebirth_idx:
        nihil_mask[max(0, ri - nihil_steps):ri] = True

    psi = np.zeros(len(t), dtype=complex)
    psi[0] = psi0

    # Pre-compute kicks deterministically by iterating chaos_state
    kick_phases = {}
    for ri in rebirth_idx:
        chaos_state = logistic_r * chaos_state * (1 - chaos_state)
        # Phase = chaos × 2π, modulated by (1-C)
        kick_phases[ri] = (1.0 - C) * 2*np.pi * chaos_state

    for i in range(1, len(t)):
        if nihil_mask[i]:
            psi[i] = 0.0
            continue
        psi[i] = psi[i-1] * np.exp(1j*omega_d*dt) * (1 - gamma*dt)
        if i in kick_phases:
            # Kick phase also coupled to pre-nihil field state — true feedback
            phi_kick = kick_phases[i] + C * np.angle(psi[i-1] + 1e-12)
            psi[i] += M_strength * np.exp(1j * phi_kick)
    return t, psi, rebirth_idx, period_r

# ============================================================
# (1) Information gain per cycle — S_n as Shannon entropy
# ============================================================
def cycle_information_gain(psi, rebirth_idx, dt, n_bins=16):
    """
    For each cycle, build a feature vector from the trajectory between
    successive rebirths (peak |ψ|, mean phase, phase drift, variance).
    Then compute the Shannon entropy of the cycle distribution in
    feature space. Higher H = more information generated per cycle.
    """
    if len(rebirth_idx) < 3:
        return 0.0, []
    features = []
    for k in range(len(rebirth_idx) - 1):
        i0, i1 = rebirth_idx[k], rebirth_idx[k+1]
        seg = psi[i0:i1]
        if len(seg) < 5:
            continue
        amp = np.abs(seg)
        ph  = np.angle(seg)
        features.append([
            amp.max(),
            amp.mean(),
            np.abs(np.mean(np.exp(1j*ph))),
            np.std(np.unwrap(ph)),
        ])
    features = np.array(features)
    if len(features) < 4:
        return 0.0, features

    # Normalize each feature to [0,1]
    f_min = features.min(axis=0)
    f_max = features.max(axis=0)
    f_norm = (features - f_min) / (f_max - f_min + 1e-12)

    # Compute Shannon entropy via 4D histogram
    H, _ = np.histogramdd(f_norm, bins=n_bins, range=[[0,1]]*4)
    p = H.flatten() / H.sum()
    p = p[p > 0]
    S_n = -np.sum(p * np.log2(p))
    return S_n, features

# Run baseline to verify
t, psi, ri, Tr = simulate(C=0.55, f_nihil=0.10)
S_n, feats = cycle_information_gain(psi, ri, 0.001)
print(f"Baseline S_n (information per cycle, bits) = {S_n:.3f}")
print(f"Cycles analyzed = {len(feats)}")

# ============================================================
# (2) Joint sweep C × nihil — does high-control need less nothing?
# ============================================================
C_grid = np.linspace(0.30, 0.95, 14)
f_grid = np.linspace(0.0, 0.80, 17)
P_grid = np.zeros((len(C_grid), len(f_grid)))
Sn_grid = np.zeros_like(P_grid)

for i, Cv in enumerate(C_grid):
    for j, fv in enumerate(f_grid):
        t, psi, ri, _ = simulate(C=Cv, f_nihil=fv, T=20.0)
        amp = np.abs(psi)
        ph  = np.angle(psi)
        alive = amp > 0.05
        prod = float(np.mean(alive))
        if alive.sum() > 0:
            coh = np.abs(np.mean(np.exp(1j*ph[alive])))
        else:
            coh = 0.0
        Sn, _ = cycle_information_gain(psi, ri, 0.001)
        # Normalize S_n by log2(bins^features) = log2(16^4) = 16
        Sn_norm = Sn / 16.0
        P_grid[i,j] = Sn_norm * coh * prod
        Sn_grid[i,j] = Sn_norm

# Optimal nihil for each C
f_opt_by_C = f_grid[np.argmax(P_grid, axis=1)]
print("\nOptimal nihil fraction by control level:")
for Cv, fv in zip(C_grid, f_opt_by_C):
    print(f"  C={Cv:.2f}  →  f_opt = {fv:.3f}")

# ============================================================
# (3) ω_r / ω_d ratio sweep — pattern vs recursion
# ============================================================
omega_d_fixed = 2.0
ratio_grid = np.linspace(0.4, 4.5, 80)
# Use the optimum nihil and a mid-range C
f_opt = float(np.mean(f_opt_by_C))
C_use = 0.65

pattern_measure = np.zeros(len(ratio_grid))
ergodic_measure = np.zeros(len(ratio_grid))
S_by_ratio = np.zeros(len(ratio_grid))

for k, r in enumerate(ratio_grid):
    omega_r = omega_d_fixed * r
    t, psi, ri, _ = simulate(C=C_use, omega_d=omega_d_fixed, omega_r=omega_r,
                              f_nihil=f_opt, T=40.0)
    # Drop transient
    psi_s = psi[5000:]

    # Poincaré section: sample (Re, Im) at fixed phase of decoherence driver
    period_d_steps = int((2*np.pi/omega_d_fixed)/0.001)
    samples = psi_s[::period_d_steps]
    # Pattern = compact phase-space distribution (closed orbit)
    # Recursion = spread distribution (ergodic)
    if len(samples) > 4:
        spread = np.std(samples.real) + np.std(samples.imag)
        # Pattern indicator: 1/spread (inverse) — high when compact
        pattern_measure[k] = 1.0 / (spread + 0.05)
        # Ergodic indicator: spread itself
        ergodic_measure[k] = spread

    Sn, _ = cycle_information_gain(psi, ri, 0.001)
    S_by_ratio[k] = Sn / 16.0

# Identify rational-ratio attractors
rational_ratios = [(1,2), (1,1), (3,2), (2,1), (5,2), (3,1), (7,2), (4,1)]
rational_vals = [num/den for num, den in rational_ratios]

# ============================================================
# Visualization
# ============================================================
fig = plt.figure(figsize=(13, 11))
fig.patch.set_facecolor('#0a0a0f')
gs = fig.add_gridspec(3, 2, hspace=0.42, wspace=0.28)

def style(ax):
    ax.set_facecolor('#0a0a0f')
    for s in ax.spines.values(): s.set_color('#6a6a8a')
    ax.tick_params(colors='#b8b8d0')
    ax.xaxis.label.set_color('#d8d8ee')
    ax.yaxis.label.set_color('#d8d8ee')
    ax.title.set_color('#e8e8ff')
    ax.grid(True, alpha=0.15, color='#5a5a7a')

# (a) Joint C × nihil product landscape
ax = fig.add_subplot(gs[0, :])
im = ax.imshow(P_grid, aspect='auto', origin='lower',
               extent=[f_grid.min(), f_grid.max(), C_grid.min(), C_grid.max()],
               cmap='magma', interpolation='bilinear')
ax.plot(f_opt_by_C, C_grid, color='#5affc0', lw=1.6, marker='o', ms=5,
        label='optimal nihil per control level')
ax.set_xlabel('forced nihil fraction f')
ax.set_ylabel('control efficiency C')
ax.set_title('Product landscape P(C, f) — green curve traces optimal nothing per control')
ax.legend(facecolor='#15151f', edgecolor='#5a5a7a', labelcolor='#d8d8ee', loc='upper right')
cb = plt.colorbar(im, ax=ax)
cb.set_label('product P = S_n · coherence · productive', color='#d8d8ee')
cb.ax.yaxis.set_tick_params(color='#b8b8d0')
plt.setp(plt.getp(cb.ax.axes, 'yticklabels'), color='#d8d8ee')
style(ax)

# (b) Optimal nihil vs C — direct test of hypothesis
ax = fig.add_subplot(gs[1, 0])
ax.plot(C_grid, f_opt_by_C, color='#ffd35a', lw=1.6, marker='o', ms=6)
# Linear fit
coef = np.polyfit(C_grid, f_opt_by_C, 1)
ax.plot(C_grid, np.polyval(coef, C_grid), color='#ff5aa0', lw=0.8, ls='--',
        label=f'slope = {coef[0]:+.3f}')
ax.set_xlabel('control efficiency C')
ax.set_ylabel('optimal nihil fraction f*')
ax.set_title('Does high control need less nothing?')
ax.legend(facecolor='#15151f', edgecolor='#5a5a7a', labelcolor='#d8d8ee')
style(ax)

# (c) Information gain S_n per cycle vs C
ax = fig.add_subplot(gs[1, 1])
Sn_opt_by_C = np.array([Sn_grid[i, np.argmax(P_grid[i])] for i in range(len(C_grid))])
ax.plot(C_grid, Sn_opt_by_C, color='#5ad8ff', lw=1.6, marker='s', ms=6)
ax.set_xlabel('control efficiency C')
ax.set_ylabel('S_n at optimum (bits / cycle, normalized)')
ax.set_title('Information gain per cycle at each optimum')
style(ax)

# (d) ω_r / ω_d sweep — pattern vs recursion
ax = fig.add_subplot(gs[2, :])
ax2 = ax.twinx()
ax.plot(ratio_grid, pattern_measure / pattern_measure.max(),
        color='#5affc0', lw=1.2, label='pattern measure (compact phase-space)')
ax.plot(ratio_grid, ergodic_measure / ergodic_measure.max(),
        color='#ff5aa0', lw=1.2, label='ergodic measure (spread)')
ax2.plot(ratio_grid, S_by_ratio, color='#ffd35a', lw=0.9, alpha=0.7,
         label='information gain S_n')
for rv, (n,d) in zip(rational_vals, rational_ratios):
    if 0.4 <= rv <= 4.5:
        ax.axvline(rv, color='#9090b0', lw=0.4, ls=':', alpha=0.6)
        ax.text(rv, 1.02, f'{n}:{d}', color='#9090b0', fontsize=8,
                ha='center', va='bottom')
ax.set_xlabel('ω_r / ω_d ratio')
ax.set_ylabel('normalized measure', color='#d8d8ee')
ax2.set_ylabel('S_n (bits/cycle)', color='#ffd35a')
ax2.tick_params(colors='#ffd35a')
ax.set_title('Frequency-ratio sweep — where pattern wins over recursion (gridlines at rational ratios)')
lines1, labels1 = ax.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()
ax.legend(lines1+lines2, labels1+labels2,
          facecolor='#15151f', edgecolor='#5a5a7a', labelcolor='#d8d8ee', loc='upper right')
style(ax)
for s in ax2.spines.values(): s.set_color('#6a6a8a')

fig.suptitle('Nihiline recursion — deterministic chaos, information per cycle, control–nothing tradeoff, pattern frequencies',
             color='#e8e8ff', fontsize=12, y=0.995)
plt.savefig('/mnt/user-data/outputs/nihiline_full_analysis.png', dpi=140,
            facecolor='#0a0a0f', bbox_inches='tight')

# Find peak pattern ratios
peak_idx = np.argsort(pattern_measure)[-5:][::-1]
print("\nTop 5 ω_r/ω_d ratios maximizing pattern (compact phase-space):")
for i in peak_idx:
    print(f"  ratio = {ratio_grid[i]:.3f}   pattern = {pattern_measure[i]:.3f}   S_n = {S_by_ratio[i]:.3f}")

print("\nHypothesis test — slope of f_opt(C):")
print(f"  slope = {coef[0]:+.4f}")
print(f"  → {'CONFIRMED: high control needs less nothing' if coef[0] < -0.01 else ('REJECTED: high control needs MORE nothing' if coef[0] > 0.01 else 'NULL: control does not affect required nothing')}")
